/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2018-10-09 03:57:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>阿甲商城学子详情页</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/header.css\"/>\r\n");
      out.write("    <link href=\"../css/pro_details.css\" rel=\"Stylesheet\"/>\r\n");
      out.write("    <link href=\"../css/animate.css\" rel=\"Stylesheet\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/footer.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "commons/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- 内容-->\r\n");
      out.write("<!--细节导航-->\r\n");
      out.write("<div id=\"nav_detail\">\r\n");
      out.write("    <h5>首页 > 学习用品 > 笔记本电脑 > 联想Lenovo-YOGA 700></h5>\r\n");
      out.write("</div>\r\n");
      out.write("<!--产品预览-->\r\n");
      out.write("<div id=\"shop_detail\">\r\n");
      out.write("    <!-- 左侧-->\r\n");
      out.write("    <div id=\"preview\" class=\"lf\">\r\n");
      out.write("        <div id=\"mediumDiv\">\r\n");
      out.write("        <!--  -->\r\n");
      out.write("            <img id=\"mImg\" \r\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paramData[1].params[0].form}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"icon_all\">\r\n");
      out.write("            <ul id=\"icon_list\">\r\n");
      out.write("            <!-- ajia_item_param_data param_data\r\n");
      out.write("            [{group:主体,params:[]},{group:图片,params:[{key:,form:},{}]}]\r\n");
      out.write("             -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 右侧-->\r\n");
      out.write("    <div class=\"right_detail lf\">\r\n");
      out.write("        <!-- 商品名称-->\r\n");
      out.write("        <h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ajiaItem.model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h1>\r\n");
      out.write("        <!-- 商品全称-->\r\n");
      out.write("        <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ajiaItem.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h3>\r\n");
      out.write("        <!-- 价格部分-->\r\n");
      out.write("        <div class=\"price\">\r\n");
      out.write("            <div id=\"pro_price\"><b>学员售价：</b>\r\n");
      out.write("            <span>￥");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ajiaItem.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></div>\r\n");
      out.write("            <div class=\"promise\">\r\n");
      out.write("                <b>服务承诺：</b>\r\n");
      out.write("                <span>*退货补运费</span>\r\n");
      out.write("                <span>*30天无忧退货</span>\r\n");
      out.write("                <span>*48小时快速退款</span>\r\n");
      out.write("                <span>*72小时发货</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 参数部分 客服-->\r\n");
      out.write("        <p class=\"parameter\">\r\n");
      out.write("            <b>客服：</b>\r\n");
      out.write("            <span class=\"connect\">联系客服</span><img class=\"gif\" src=\"../images/product_detail/kefuf.gif\">\r\n");
      out.write("        </p>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <!-- 未选择规格，颜色时状态-->\r\n");
      out.write("        <div class=\"message\"></div>\r\n");
      out.write("        <!-- 数量-->\r\n");
      out.write("        <p class=\"accountChose\">\r\n");
      out.write("            <s>数量：</s>\r\n");
      out.write("            <button class=\"numberMinus\">-</button>\r\n");
      out.write("            <input type=\"text\" value=\"1\" class=\"number\" id=\"buy-num\">\r\n");
      out.write("            <button class=\"numberAdd\">+</button>\r\n");
      out.write("        </p>\r\n");
      out.write("        <!-- 购买部分-->\r\n");
      out.write("        <div class=\"shops\">\r\n");
      out.write("            <a href=\"cart.html\" class=\"buy lf\" id=\"buy_now\">立即购买</a>\r\n");
      out.write("            <a href=\"#\" class=\"shop lf\" id=\"add_cart\"><img src=\"../images/product_detail/product_detail_img7.png\" alt=\"\"/>加入购物车</a>\r\n");
      out.write("            <a href=\"#\" class=\"collection lf\" id=\"collect\"><span>收藏</span></a><b><img src=\"../images/product_detail/product_detail_img6.png\"                                                                       alt=\"\"/></b>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--为你推荐-->\r\n");
      out.write("<div id=\"recommended\">\r\n");
      out.write("    <p>为你推荐<span>大家都在看</span></p>\r\n");
      out.write("    <div id=\"demo\" style=\"width:1000px;overflow:hidden;\">\r\n");
      out.write("        <div id=\"indemo\" style=\"float: left;width: 200%;\">\r\n");
      out.write("            <div id=\"demo1\" style=\"float:left\"><!-- 第一个宽度显示 -->\r\n");
      out.write("                 <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_1.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>ThinkPad New S2 (20GUA00QCD)13.3英寸超霸</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_2.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>戴尔 DELL燃7000 R1605S 超霸</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_3.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>戴尔(DELL)魔方15MF Pro-R2505TSS灵</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_4.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>联想(Lenovo) YOGA900 (YOGA4 PRO)多彩版</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--</div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"demo2\" style=\"float:left\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 宽度超大 -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 外面大框 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--商品详情-->\r\n");
      out.write("<div id=\"iteminfo\">\r\n");
      out.write("    <div id=\"tab\">\r\n");
      out.write("        <div class=\"tab lf\">\r\n");
      out.write("            <div class=\"cat\">\r\n");
      out.write("                <span class=\"active\"><a href=\"\">商品详情</a></span>\r\n");
      out.write("                <span><a href=\"lookforward.html\">商品评价</a></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart rt\">\r\n");
      out.write("            <img src=\"../images/product_detail/product_detail_img9.png\" alt=\"\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"left lf\">\r\n");
      out.write("        <div class=\"all\">\r\n");
      out.write("            <!--<p><img src=\"images_x/pin_logo.png\" alt=\"\"/></p>-->\r\n");
      out.write("            <div id=\"parm\">\r\n");
      out.write("                <div id=\"specification_parameter\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        规格参数\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_icon_1.png\" alt=\"\" class=\"ys5\"/>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <!--<img src=\"images_x/canshu.png\" alt=\"\" class=\"ys5\"/>-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">商品名称：联想YOGA 710</a></li>\r\n");
      out.write("                    <li><a href=\"#\">系统：windows10</a></li>\r\n");
      out.write("                    <li><a href=\"#\">内存容量：8G</a></li>\r\n");
      out.write("                    <li><a href=\"#\">分辨率：全清高屏(1920*1080)</a></li>\r\n");
      out.write("                    <li><a href=\"#\">显卡型号：GT940M</a></li>\r\n");
      out.write("                    <li><a href=\"#\">处理器：Intel i7低功耗版</a></li>\r\n");
      out.write("                    <li><a href=\"#\">显存容量：2G</a></li>\r\n");
      out.write("                    <li><a href=\"#\">分类：清薄本</a></li>\r\n");
      out.write("                    <li><a href=\"#\">硬盘容量:256G固态</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"product_introduction\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    商品介绍\r\n");
      out.write("                    <img src=\"../images/product_detail/product_detail_icon_4.png\" alt=\"\" class=\"ys5\"/>\r\n");
      out.write("                </p>\r\n");
      out.write("                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${desc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"sale_protection\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    售后保障\r\n");
      out.write("                    <img src=\"../images/product_detail/product_detail_icon_3.png\" alt=\"\" class=\"ys5\"/>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"sale_content\">\r\n");
      out.write("                    <p class=\"paper\" id=\"sale_protect\">\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_img16.png\" alt=\"\"/>\r\n");
      out.write("                        正品保障\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"content\">\r\n");
      out.write("                        阿甲学子商城向您保证所售商品均为正品行货，阿甲自营商品开具机打发票或电子发票。\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"paper\">\r\n");
      out.write("                        <img src=\"../images/product_detail/product_detail_img16.png\" alt=\"\"/>\r\n");
      out.write("                        全国联保\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"content\">\r\n");
      out.write("                        凭质保证书及阿甲商城发票，可享受全国联保服务，与您亲临商场选购的商品享受相同的质量保证。阿甲商城还为您提供具有竞争力的商品价格和运费政策，请您放心购买！\r\n");
      out.write("                        注：因厂家会在没有任何提前通知的情况下更改产品包装、产地或者一些附件，本司不能确保客户收到的货物与商城图片、产地、附件说明完全一致。只能确保为原厂正货！并且保证与当时市场上同样主流新品一致。若本商城没有及时更新，请大家谅解！\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"packing_list\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    包装清单\r\n");
      out.write("                    <img src=\"../images/product_detail/product_detail_icon_2.png\" alt=\"\" class=\"ys5\"/>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"content\">笔记本 x1 适配器 x1 电源线 x1 电池 x1 说明书（电子版）x1 备注：笔记本电脑的背面只会标注此电脑的系列，例如： XPS 13-9360 ，\r\n");
      out.write("                    如果您需要核实此电脑的具体配置型号是否与阿甲页面相符，可电话咨询阿甲厂商：800-858-2969</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"right rt\">\r\n");
      out.write("        <div class=\"aside_nav\">\r\n");
      out.write("            <p><i><img src=\"../images/product_detail/product_detail_icon_g_1.png\" alt=\"\"/></i><a href=\"#specification_parameter\">规格参数</a></p>\r\n");
      out.write("            <p><i><img src=\"../images/product_detail/product_detail_icon_t_1.png\" alt=\"\"/></i><a href=\"#product_introduction\">商品介绍</a></p>\r\n");
      out.write("            <p><i><img src=\"../images/product_detail/product_detail_icon_d_1.png\" alt=\"\"/></i><a href=\"#sale_protection\">售后保障</a></p>\r\n");
      out.write("            <p><i><img src=\"../images/product_detail/product_detail_icon_bao_1.png\" alt=\"\"/></i><a href=\"#sale_protect\">包装清单</a></p>\r\n");
      out.write("            <p><i><img src=\"../images/product_detail/product_detail_icon_up_1.png\" alt=\"\"/></i><a href=\"#\">回到顶部</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 品质保障，私人定制等-->\r\n");
      out.write("<div id=\"foot_box\">\r\n");
      out.write("    <div class=\"icon1 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon1.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>品质保障</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon2 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon2.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>私人定制</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon3 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon3.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>学员特供</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon4 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon4.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>专属特权</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 页面底部-->\r\n");
      out.write("<div class=\"foot_bj\">\r\n");
      out.write("    <div id=\"foot\">\r\n");
      out.write("        <div class=\"lf\">\r\n");
      out.write("            <p class=\"footer1\"><img src=\"../images/footer/logo.png\" alt=\"\" class=\" footLogo\"/></p>\r\n");
      out.write("            <p class=\"footer2\"><img src=\"../images/footer/footerFont.png\"alt=\"\"/></p>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"foot_left lf\" >\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><h3>买家帮助</h3></a></li>\r\n");
      out.write("                <li><a href=\"#\">新手指南</a></li>\r\n");
      out.write("                <li><a href=\"#\">服务保障</a></li>\r\n");
      out.write("                <li><a href=\"#\">常见问题</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><h3>商家帮助</h3></a></li>\r\n");
      out.write("                <li><a href=\"#\">商家入驻</a></li>\r\n");
      out.write("                <li><a href=\"#\">商家后台</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><h3>关于我们</h3></a></li>\r\n");
      out.write("                <li><a href=\"#\">关于阿甲</a></li>\r\n");
      out.write("                <li><a href=\"#\">联系我们</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"../images/footer/wechat.png\" alt=\"\"/>\r\n");
      out.write("                    <img src=\"../images/footer/sinablog.png\" alt=\"\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"service\">\r\n");
      out.write("            <p>阿甲商城客户端</p>\r\n");
      out.write("            <img src=\"../images/footer/ios.png\" class=\"lf\">\r\n");
      out.write("            <img src=\"../images/footer/android.png\" alt=\"\" class=\"lf\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"download\">\r\n");
      out.write("            <img src=\"../images/footer/erweima.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<!-- 页面底部-备案号 #footer -->\r\n");
      out.write("            <div class=\"record\">\r\n");
      out.write("                &copy;2017 阿甲集团有限公司 版权所有 京ICP证xxxxxxxxxxx\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal\" style=\"display:none\">\r\n");
      out.write("    <div class=\"modal_dialog\">\r\n");
      out.write("        <div class=\"modal_header\">\r\n");
      out.write("              操作提醒\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal_information\">\r\n");
      out.write("            <img src=\"../images/model/model_img2.png\" alt=\"\"/>\r\n");
      out.write("            <span>是否将您的宝贝加入收藏夹</span>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"yes\"><span>确定</span></div>\r\n");
      out.write("        <div class=\"no\"><span>取消</span></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"../js/index.js\"></script>\r\n");
      out.write("<!--图片轮播悬停进入详情页效果-->\r\n");
      out.write("<script>\r\n");
      out.write("    var speed = 20;\r\n");
      out.write("    var tab = document.getElementById(\"demo\");\r\n");
      out.write("    var tab1 = document.getElementById(\"demo1\");\r\n");
      out.write("    var tab2 = document.getElementById(\"demo2\");\r\n");
      out.write("    tab2.innerHTML = tab1.innerHTML;\r\n");
      out.write("    function Marquee() {\r\n");
      out.write("        if (tab2.offsetWidth - tab.scrollLeft <= 0)\r\n");
      out.write("            tab.scrollLeft -= tab1.offsetWidth\r\n");
      out.write("        else {\r\n");
      out.write("            tab.scrollLeft++;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    var MyMar = setInterval(Marquee, speed);\r\n");
      out.write("    tab.onmouseover = function () {\r\n");
      out.write("        clearInterval(MyMar)\r\n");
      out.write("    };\r\n");
      out.write("    tab.onmouseout = function () {\r\n");
      out.write("        MyMar = setInterval(Marquee, speed)\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("<!--添加到购物车 立即购买 收藏部分-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //加入购物车操作\r\n");
      out.write("    var color;\r\n");
      out.write("    var norms;\r\n");
      out.write("    var buyAccount;\r\n");
      out.write("    function getPro(){\r\n");
      out.write("    \t//颜色取值\r\n");
      out.write("        $(\"#choose_color input\").each(function (i, item) {\r\n");
      out.write("            if ($(this).hasClass(\"borderChange\")) {\r\n");
      out.write("                color = $(this).val();\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        console.log(color)\r\n");
      out.write("        //规格取值\r\n");
      out.write("        $(\".avenge\").each(function () {\r\n");
      out.write("            if ($(this).hasClass(\"borderChange\")) {\r\n");
      out.write("                norms = $(this).html();\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        console.log(norms)\r\n");
      out.write("        //数量取值\r\n");
      out.write("        buyAccount = $(\"#buy-num\").val();\r\n");
      out.write("        console.log(buyAccount);\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#add_cart\").click(function (e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        getPro();\r\n");
      out.write("        //如果未选择，请选择商品信息\r\n");
      out.write("        if (!color || !norms ) {\r\n");
      out.write("//            $(\"#add_cart\").text(\"加入购物车\").css({\"background\":\"#f5f5f5\",\"color\":\"#000\"})\r\n");
      out.write("            alert(\"请选择商品信息\");\r\n");
      out.write("        }else{\r\n");
      out.write("        \t$(\".modal\").show();\r\n");
      out.write("        \t$(\".modal_information span\").html(\"是否将您的宝贝加入购物车\");\r\n");
      out.write("        }\r\n");
      out.write("        $('.no').click(function(){\r\n");
      out.write("        \t$('.modal').hide();\r\n");
      out.write("        })\r\n");
      out.write("        $('.yes').click(function(){\r\n");
      out.write("        \t$('.modal').hide();\r\n");
      out.write("        \t\r\n");
      out.write("        \tvar params = {\r\n");
      out.write("                    num: buyAccount,\r\n");
      out.write("        \t\t\titemId:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("                };\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/cart/insert.html\",\r\n");
      out.write("                    data: params,\r\n");
      out.write("                    dataType:\"json\",\r\n");
      out.write("                    success: function (data) {\r\n");
      out.write("                        if (data.status == 200) {\r\n");
      out.write("                            alert(\"添加购物车成功！\");\r\n");
      out.write("                        } else if (data.status == 500) {\r\n");
      out.write("                            alert(\"添加购物车失败！\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert(\"您还没登录呢！\");\r\n");
      out.write("                            window.location.href = data;\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function (data) {\r\n");
      out.write("                    alert(\"联网失败！\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("    })\r\n");
      out.write("    /**添加到收藏**/\r\n");
      out.write("    $(\"#collect\").click(function (e){\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        getPro();\r\n");
      out.write("          //如果未选择，请选择商品信息\r\n");
      out.write("\t\tif (!color || !norms ) {\r\n");
      out.write("\t\t\talert(\"请选择宝贝的参数信息\");\r\n");
      out.write("        }else{\r\n");
      out.write("            $(\".modal\").show();\r\n");
      out.write("            $(\".modal_information span\").html(\"是否将您的宝贝加入收藏夹\");\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    $('.no').click(function(){\r\n");
      out.write("        $('.modal').hide();\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        var nav = $(\"#tab\"); //得到导航对象\r\n");
      out.write("        var aside = $(\".aside_nav\");//右侧导航\r\n");
      out.write("        var win = $(window); //得到窗口对象\r\n");
      out.write("        var sc = $(document);//得到document文档对象。\r\n");
      out.write("        win.scroll(function () {\r\n");
      out.write("            if (sc.scrollTop() >= 1000) {\r\n");
      out.write("                nav.addClass(\"fixed_tab\");\r\n");
      out.write("                aside.addClass(\"fixed_aside\");\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                nav.removeClass(\"fixed_tab\");\r\n");
      out.write("                aside.removeClass(\"fixed_aside\");\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        win.scroll(function () {\r\n");
      out.write("            if (sc.scrollTop() >= 60 && sc.scrollTop() < 1000){\r\n");
      out.write("                $(\"#top\").addClass(\"fixed_nav\");\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                $(\"#top\").removeClass(\"fixed_nav\");\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        //介绍区域右侧导航\r\n");
      out.write("        $(\"#iteminfo .right p\").click(function () {\r\n");
      out.write("            //$(this).addClass(\"clic\").siblings().removeClass(\"clic\");\r\n");
      out.write("            $(this).css(\"background-color\", \"#0AA1ED\").siblings().css(\"background-color\", \"#e8e8e8\");\r\n");
      out.write("            $(this).find(\"a\").css(\"color\", \"#fff\").parent().siblings().find(\"a\").css(\"color\", \"#828282\")\r\n");
      out.write("        })\r\n");
      out.write("        /**选择商品进行添加 悬停效果**/\r\n");
      out.write("        $(\".avenge\").mouseover(function () {\r\n");
      out.write("            $(this).css({\"border\": \"1px solid #0AA1ED\", \"color\": \"#0AA1ED\"});\r\n");
      out.write("        }).mouseout(function () {\r\n");
      out.write("            $(this).css({\"border\": \"1px solid #666\", \"color\": \"#666\"})\r\n");
      out.write("        })\r\n");
      out.write("        /**数量添加**/\r\n");
      out.write("        var n = $(\"#buy-num\").val() * 1;\r\n");
      out.write("        $(\".numberMinus\").click(function () {\r\n");
      out.write("            if (n >= 1) {\r\n");
      out.write("                $(\"#buy-num\").val(n -= 1);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        $(\".numberAdd\").click(function () {\r\n");
      out.write("            $(\"#buy-num\").val(n += 1);\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        /**ajax提交**/\r\n");
      out.write("        $(\".avenge\").each(function (i, item) {\r\n");
      out.write("            $(this).click(function (norms) {\r\n");
      out.write("                $(this).addClass(\"borderChange\")\r\n");
      out.write("                if ($(this).siblings().addClass(\"borderChange\")) {\r\n");
      out.write("                    $(this).siblings().removeClass(\"borderChange\")\r\n");
      out.write("                }\r\n");
      out.write("                //规格选择\r\n");
      out.write("                var norms = $(this).html();\r\n");
      out.write("                console.log(norms)\r\n");
      out.write("                //商品类型id\r\n");
      out.write("                var itemParamId=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemParamId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("                console.log(itemParamId);\r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                var $selectInput=$(\"#choose_color input.borderChange\");\r\n");
      out.write("                var color=$selectInput.val();\r\n");
      out.write("                getItemId(color,norms,itemParamId);\r\n");
      out.write("                \r\n");
      out.write("                //}\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("        function getItemId(color,model,itemParamId)\r\n");
      out.write("        {\r\n");
      out.write("        \tvar url=\"/item/getItemId.html\";\r\n");
      out.write("            var param={\"color\":color,\r\n");
      out.write("            \t\t\"model\":model,\r\n");
      out.write("            \t\t\"itemParamId\":itemParamId};\r\n");
      out.write("            $.ajax({\r\n");
      out.write("            \t\"url\":url,\r\n");
      out.write("            \t\"type\":\"POST\",\r\n");
      out.write("            \t\"data\":param,\r\n");
      out.write("            \t\"dataType\":\"json\",\r\n");
      out.write("            \t\"success\":function(response)\r\n");
      out.write("            \t{\r\n");
      out.write("            \t\tvar itemId=response.data;\r\n");
      out.write("            \t\tvar url=\"/item/toItemInfo.html?itemId=\"+itemId;\r\n");
      out.write("            \t\tlocation.href=url;\r\n");
      out.write("            \t},\r\n");
      out.write("            \t\"error\":function(e)\r\n");
      out.write("            \t{\r\n");
      out.write("            \t\talert(\"联网失败\");\r\n");
      out.write("            \t}\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        //颜色选择\r\n");
      out.write("        $(\"#choose_color input\").each(function (i, item) {\r\n");
      out.write("            $(this).click(function () {\r\n");
      out.write("                $(this).addClass(\"borderChange\")\r\n");
      out.write("                if ($(this).siblings().addClass(\"borderChange\")) {\r\n");
      out.write("                    $(this).siblings().removeClass(\"borderChange\")\r\n");
      out.write("                }\r\n");
      out.write("                var color = $(this).val();\r\n");
      out.write("                console.log(color)\r\n");
      out.write("                var $span=$(\".avenge.borderChange\");\r\n");
      out.write("                var model=$span.html();\r\n");
      out.write("                console.log(model);\r\n");
      out.write("                var itemParamId=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemParamId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("                getItemId(color,model,itemParamId);\r\n");
      out.write("                \r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("        //数量选择\r\n");
      out.write("        $(\".accountChose\").click(function () {\r\n");
      out.write("            var buyAccount = $(\"#buy-num\").val();\r\n");
      out.write("            console.log(buyAccount);\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        /*立即购买*/\r\n");
      out.write("        $(\"#buy_now\").click(function (e) {\r\n");
      out.write("            //如果未选择，请选择商品信息\r\n");
      out.write("            if (color == undefined && norms == undefined) {\r\n");
      out.write("//            $(\"#add_cart\").text(\"加入购物车\").css({\"background\":\"#f5f5f5\",\"color\":\"#000\"})\r\n");
      out.write("                alert(\"请选择商品信息\");\r\n");
      out.write("            }else{\r\n");
      out.write("                location.href=\"cart.html\";\r\n");
      out.write("            }\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            var color = $(\"#choose_color input.borderChange\").val();\r\n");
      out.write("            var model = $(\"#choose_model span.borderChange\").html();\r\n");
      out.write("            var num = $(\"#buy-num\").val();\r\n");
      out.write("            // 后台需要的参数\r\n");
      out.write("            // var url = '/toOrder/'+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("+'.html?&num='+num+'&itemColor='+color+'&itemModel='+model;\r\n");
      out.write("//             window.location.href = url;\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("<!--图片效果-->\r\n");
      out.write("<script>\r\n");
      out.write("    $(\"#mImg\").hover(function (){\r\n");
      out.write("        $(this).addClass(\"animated pulse\");\r\n");
      out.write("    }, function (){\r\n");
      out.write("        $(this).removeClass(\"animated pulse\");\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    $('#icon_list>li').click(function(){\r\n");
      out.write("        $(this).children('img').css('border','1px solid #CECFCE');\r\n");
      out.write("        var address=$(this).children().attr('src');\r\n");
      out.write("        console.log(address);\r\n");
      out.write("        var newaddress=address.slice(0,-4);\r\n");
      out.write("        var bigaddress=newaddress+'_big.png';\r\n");
      out.write("        $('#mImg').attr('src',bigaddress);\r\n");
      out.write("        $(this).siblings().children('img').css('border','');\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/product_details.jsp(38,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/product_details.jsp(38,12) '${paramData[1].params}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${paramData[1].params}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/product_details.jsp(38,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("icon");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li class=\"i1\">\r\n");
          out.write("                <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icon.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"/>\r\n");
          out.write("                </li>\r\n");
          out.write("             ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/jsp/product_details.jsp(70,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/product_details.jsp(70,8) '${typeParamData[0].params}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${typeParamData[0].params}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/product_details.jsp(70,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("typeParam");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("         ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/jsp/product_details.jsp(72,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${typeParam.key=='颜色'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <!-- 颜色-->\r\n");
        out.write("        <p class=\"style\" id=\"choose_color\">\r\n");
        out.write("            <s class=\"color\">颜色：</s>\r\n");
        out.write("            ");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("         </p>\r\n");
        out.write("         ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/jsp/product_details.jsp(76,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${typeParam.values!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            ");
        if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/jsp/product_details.jsp(77,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/product_details.jsp(77,12) '${typeParam.values}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${typeParam.values}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/product_details.jsp(77,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("color");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <input type=\"button\" class=\"i1 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color==itemColor?'borderChange':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" \r\n");
          out.write("            value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" title=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"/>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/jsp/product_details.jsp(85,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${typeParam.key=='型号'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <!-- 规格-->\r\n");
        out.write("        <p>\r\n");
        out.write("            <s>型号：</s>\r\n");
        out.write("            ");
        if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("            \r\n");
        out.write("        </p>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/jsp/product_details.jsp(89,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${typeParam.values!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            ");
        if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fif_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /WEB-INF/jsp/product_details.jsp(90,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/product_details.jsp(90,12) '${typeParam.values}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${typeParam.values}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/product_details.jsp(90,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("model");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <span class=\"avenge ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model==itemModel?'borderChange':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }
}
